### PR TITLE
Bubble sort feature

### PR DESCRIPTION
**Pull request by German-Cobian**
Bubble-sort is a program that takes in an array and sorts it according to a given parameter two elements at a time using nested loops.

### CODE REVIEW

**Comment by Mihndim2020** [comment]
The highlighted linter errors are NOT actually errors but proposals that are not in conformity with the code, it doesn't work(can not be implemented) with code. Please have a look and give us feedback on that. Thank you.

**Review by enaburekhan — COMMENTED** [review]
# Status: Invalid
Hi team!
Friendly reminder: You should make sure that your repo looks professional by passing all linters check before review.
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

I took the extra time to clone the repository. Rubocop was trying to enforce the best ruby practice to the codebase. 
Your first method can be refactored to use fewer lines of code. Always avoid using a loop like for loop. There are better alternatives called iterables like each, each_with_index, etc. Do some research on the errors you are getting and allow rubocop help you write better codes.

**Comment by Mihndim2020** [comment]
Changes effected as requested

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @German-Cobian and @Mihndim2020 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Update README file like suggested [README file](https://github.com/microverseinc/readme-template).
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Mihndim2020** [comment]
Changes effected as requested. Readme file updated

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] Great job implementing all of the feedback. 💯
  - [x] Code shows a great understanding of loops in ruby.💯
- ### To Improve  
  - [ ] [OPTIONAL] Please include the steps to be followed to run this project locally in your README.


_Congratulations on the splendid job **@team** 👍
You can now merge to master and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
###  _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), @slack: Rukundo Eric**

**Pull request merged**
